apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
      - name: semua server
        rules:
          - alert: CPU 50 persen
            expr: ((sum by(instance) (irate(node_cpu_seconds_total{mode!="idle"}[15s])) / sum by (instance)((irate(node_cpu_seconds_total{}[15s])))) * 100) >= 50
            for: 30s # kurun waktu untuk sebuah expresi dianggap valid
            labels:
              # label ini penting untuk mapping notifikasi di Alertmanager
              severity: critical
            annotations:
              # berisi informasi dari sebuah alert
              summary: CPU nyentuh 50% selama 30 detik terkahir gess dari kubernetes!!!
  prometheus.yml: |-
    global:
      scrape_interval: 5s

      evaluation_interval: 3s # waktu interval evaluasi dari setiap rule monitoring

    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
    - job_name: server-linux-via-dns
      dns_sd_configs:
        - names:
            - prometheus-target.cobasaja.biz.id
          type: A
          port: 9100
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: endpoints 
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
              - 'alertmanager.monitoring.svc:9093'


